### Numpy Array Operations


In [4]:
import numpy as np

In [8]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("Original array:", arr[2:7]) #slicing from index 2 to 6
print("Sliced array:", arr[2:7:2]) #step of 2
print("NEGATIVE SLICING", arr[-2]) #negative indexing to get the second last element
print("NEGATIVE SLICING", arr[-2:]) #slicing from the second

Original array: [3 4 5 6 7]
Sliced array: [3 5 7]
NEGATIVE SLICING 9
NEGATIVE SLICING [ 9 10]


In [11]:
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

print("2D Array Slicing:", arr_2d[1,2])
print("2D Array Slicing:", arr_2d[: ,1])

2D Array Slicing: 6
2D Array Slicing: [2 5 8]


### sorting

In [23]:
unsorted = np.array([3,1,7,8,5])
print("sorted Array:", np.sort(unsorted)) #sorts the array in ascending order

arr_2d_unsorted = np.array([[3,1,7],
                            [8,5,2],
                            [6,4,9]])

print("2D Array sorted:", np.sort(arr_2d_unsorted, axis=0)) #sorts each column in ascending order

sorted Array: [1 3 5 7 8]
2D Array sorted: [[3 1 2]
 [6 4 7]
 [8 5 9]]


### filering

In [24]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_no = numbers[numbers % 2 == 0] #boolean indexing to get even numbers
print("Even numbers:", even_no)

Even numbers: [ 2  4  6  8 10]


### Filter with mask

In [26]:
mask = numbers > 5 #boolean mask for numbers greater than 5
print("Numbers greater than 5:", numbers[mask]) #apply mask to get numbers greaterz

Numbers greater than 5: [ 6  7  8  9 10]


#### FANCY INDEXING VS NP.WHERE()

In [31]:
indices = [0,2,4]
print(numbers[indices]) #indexing to get specific elements at indices 0, 2, and 4

where_indices = np.where(numbers > 5) #get indices of numbers greater than 5
print("NP where: ", numbers[where_indices])

[1 3 5]
NP where:  [ 6  7  8  9 10]


In [34]:
conitional_arr= np.where(numbers > 5,"True", "False") #conditional array where numbers > 5 are kept, others replaced with -1
print("Conditional Array:", conitional_arr)

Conditional Array: ['False' 'False' 'False' 'False' 'False' 'True' 'True' 'True' 'True'
 'True']


### adding or removing data

In [44]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print( arr1+ arr2) #add two arrays element-wise
print("Concatenated Array:", np.concatenate((arr1, arr2))) #concatenate two arrays

# Removing arrays

arr= np.array([1, 2, 3, 4, 5])
arr = np.delete(arr, 2) #remove element at index 2
print("Array after deletion:", arr)

[5 7 9]
Concatenated Array: [1 2 3 4 5 6]
Array after deletion: [1 2 4 5]


### array compatibilty

In [39]:
a = np.array([1, 2, 3, 4, 5])
b= np.array([2, 3])
print("Compatiblty shapes: " , a.shape==b.shape) #check if shapes are compatible for broadcasting

Compatiblty shapes:  False


In [43]:
org= np.array([[1, 2, 3], [4, 5,6 ]])
new = np.array([[6, 7, 8], [9, 10,11]])
new= np.vstack((org, new)) #vertically stack two arrays
print(new)

[[ 1  2  3]
 [ 4  5  6]
 [ 6  7  8]
 [ 9 10 11]]
