In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [10]:
array1 = np.array([1, 2, 3, 4, 5])
array2= np.random.rand(3,3)
array3= np.zeros((4,4))
np.save('array1.npy', array1)
np.save('array2.npy', array2)
np.save('array3.npy', array3)   

loaded_array1 = np.load('array1.npy')
loaded_array2 = np.load('array2.npy')
loaded_array3 = np.load('array3.npy')
print("Loaded Array 1:", loaded_array1)
print("Loaded Array 2:\n", loaded_array2) 
print("Loaded Array 3:\n", loaded_array3)                      

Loaded Array 1: [1 2 3 4 5]
Loaded Array 2:
 [[0.64410421 0.75141348 0.03425802]
 [0.48290052 0.29315475 0.73792638]
 [0.88139919 0.35932126 0.62920619]]
Loaded Array 3:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [15]:
try:
    logo = np.load('numpy-logo.npy')
    plt.figure(figsize=(10,6))
    plt.subplot(121)
    plt.imshow(logo)
    plt.title('numpy logo')
    plt.grid(False)

    dark_logo= 1-logo

    plt.subplot(122)  
    plt.imshow(dark_logo)
    plt.title('Dark numpy logo')
    plt.grid(False)
except FileNotFoundError:
    print("File not found. Please check the file path.")    

EOFError: No data left in file