In [2]:
import numpy as np
import matplotlib.pyplot as plt

### Advanced Operation with business operations

In [4]:
# Data Stru= [Restaurant_id, 2021, 2022, 2023, 2024]
data = np.array([
    [1, 100, 150, 200, 250],
    [2, 200, 250, 300, 350],            
    [3, 300, 350, 400, 450],
    [4, 400, 450, 500, 550],
    [5, 500, 550, 600, 650]
])

print("=== Zomato Restaurant Revenue Data ===")
print("\n Sales Data shape:", data.shape)
print("\n sample data for 1st 3 restaurants:\n", data[:3])

=== Zomato Restaurant Revenue Data ===

 Sales Data shape: (5, 5)

 sample data for 1st 3 restaurants:
 [[  1 100 150 200 250]
 [  2 200 250 300 350]
 [  3 300 350 400 450]]
