## Numpy array and basics
learn about numpy with me.

### creating array from list

In [12]:
import numpy as np
arr_1D = np.array([1,2,3,4,5])
print("1D array: ", arr_1D)
arr_2D = np.array([[1,2,3,4], [5,6]])
print("2D array: ", arr_2D)


1D array:  [1 2 3 4 5]


ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

### List vs numpy array


In [14]:
py_list= [1, 2, 3, 4, 5]
print("Python list: ", py_list*2)

np_list = np.array([1,2,3,4,5])   #element wise multiplication
print("Numpy array: ", np_list*2)  

Python list:  [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
Numpy array:  [ 2  4  6  8 10]


In [18]:
import time
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n Python list time: ", time.time() - start)

start = time.time()
np_list = np.arange(1000000) * 2
print("Numpy array time: ", time.time() - start)



 Python list time:  0.07902121543884277
Numpy array time:  0.0009236335754394531


### creaing array from scratch

In [25]:
zeroes = np.zeros((3, 4))
print("zeroes array: \n", zeroes)

ones = np.ones((3, 4))
print("ones array: \n", ones)

full = np.full((3, 4), 5)   #create a full array with all elements as 5
print("full array: \n", full)

random = np.random.random((3, 4))  #create a random array
print("random array: \n", random*100)

sequence = np.arange(0, 20, 2)  #create a sequence array
print("sequence array: ", sequence)



zeroes array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
full array: 
 [[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
random array: 
 [[95.7476458   9.38403263 98.84434243 15.65793317]
 [71.33347829 42.30779066 78.1694132  73.59519895]
 [26.15216472 26.04553956 82.67953249 11.87224019]]
sequence array:  [ 0  2  4  6  8 10 12 14 16 18]


### Vector, matrix, tensor

In [29]:
vector = np.array([1, 2, 3])
matrix = np.array([[1, 2, 3], 
                   [4, 5, 6]])
print("Vector: ", vector)
print("Matrix: \n", matrix)

tensor = np.array([[[1, 2], [3, 4]], 
                   [[5, 6], [7, 8]]]) 
print("Tensor: \n", tensor)

Vector:  [1 2 3]
Matrix: 
 [[1 2 3]
 [4 5 6]]
Tensor: 
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### array properties

In [34]:
arr = np.array([[1, 2, 3, 4, 5],
                [1, 2, 3, 4, 5]])

print("shape of arr: ", arr.shape)
print("size of arr: ", arr.size)
print("dtype of arr: ", arr.dtype)
print("dimensions of arr: ", arr.ndim)

shape of arr:  (2, 5)
size of arr:  10
dtype of arr:  int64
dimensions of arr:  2


### array reshaping

In [ ]:
arr= np.arange(1, 19, 2)  #create an array with a step of 2
print("Array with step of 2: ", arr)

reshaped_arr = arr.reshape((3,3)) #reshape the array to 3x3
print("Reshaped array: \n", reshaped_arr)





Array with step of 2:  [ 1  3  5  7  9 11 13 15 17]
Reshaped array: 
 [[ 1  3  5]
 [ 7  9 11]
 [13 15 17]]
